aspnet_mvc/CardCram.Client/Models/CardViewModel.cs
namespace CardCram.Client.Models
{
    public class CardViewModel
  {
    public string Question { get; set; }
    public string Answer { get; set; }  

    public DeckViewModel Deck {get; set;}

    public int CardId {get; set;}

    public int DeckId {get; set;}
  }
}

aspnet_mvc/CardCram.Client/Models/DeckViewModel.cs
using System.Collections.Generic;
using Microsoft.Extensions.Configuration;

namespace CardCram.Client.Models
{
  public class DeckViewModel
  {
    public List<CardViewModel> Cards { get; set; }
    public CardViewModel NewCard { get; set; }
    public int DeckId { get; set; }
    public string Title { get; set; }
    public DeckViewModel() {
      Cards = new List<CardViewModel>();
      }
    }
}

aspnet_mvc/CardCram.Client/Models/ErrorViewModel.cs
using System;

namespace CardCram.Client.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

aspnet_mvc/CardCram.Client/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Okta.AspNetCore;

public class AccountController : Controller
{
    public IActionResult SignIn()
    {
        if (!HttpContext.User.Identity.IsAuthenticated)
        {
            return Challenge(OktaDefaults.MvcAuthenticationScheme);
        }

        return RedirectToAction("Index", "Home");
    }
}

aspnet_mvc/CardCram.Client/Controllers/CardController.cs
using System.Net.Http;
using System.Threading.Tasks;
using CardCram.Client.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CardCram.Client.Controllers
{
    public class CardController : Controller
    {
        public string apiUrl = "https://localhost:5551/CardCram";

        private HttpClient _http = new HttpClient();

        [HttpGet]
        public async Task<IActionResult> Get()
        {
            var response = await _http.GetAsync(apiUrl);

            if (response.IsSuccessStatusCode)
            {
                var content = JsonConvert.DeserializeObject<CardViewModel>(await response.Content.ReadAsStringAsync());
                return View("CreateCard", content);
            }

            var ErrorViewModel = new ErrorViewModel();
            return View ("Error", ErrorViewModel);
        
            
        }

        [HttpGet]
        public IActionResult DeleteCard()
        {
            return View ("DeleteCard", new DeckViewModel());
        }
    }
}

aspnet_mvc/CardCram.Client/Controllers/DeckController.cs
using System;
using CardCram.Client.Models;
using Microsoft.AspNetCore.Mvc;

namespace CardCram.Client.Controllers
{
    public class DeckController : Controller
    {
        CardViewModel NewCard = new CardViewModel();
        DeckViewModel CardList = new DeckViewModel();
        [Route("[controller]/[action]")]

        [HttpGet]
        public IActionResult CreateDeck()
        {
            return View("create");
        }

        [HttpGet]
        public IActionResult DeleteDeck()
        {
            return View("delete");
        }

        public IActionResult DownloadDeck()
        {
            return View();
        }
    }
}

aspnet_mvc/CardCram.Client/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CardCram.Client.Models;
using Microsoft.AspNetCore.Authorization;


namespace CardCram.Client.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public DeckViewModel CardList;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index(DeckViewModel model)
        {
            CardList = model;
            foreach (var item in CardList.Cards)
            {
                System.Console.WriteLine(item.Question);
            }
            return View(CardList);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

aspnet_mvc/CardCram.Client/Views/Card/Create.cshtml
@model CardCram.Client.Models.DeckViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Your Card</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="create" asp-controller="card" asp-antiforgery="true" method="GET">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" name="NewCard.DeckId" value="@ViewBag.DeckId"/>
            </div>
            <div class="form-group">
                <label asp-for="NewCard.Question" class="control-label"></label>
                <input asp-for="NewCard.Question" class="form-control"/>
                <span asp-validation-for="NewCard.Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NewCard.Answer" class="control-label"></label>
                <input asp-for="NewCard.Answer" class="control-label"/>
                <span asp-validation-for="NewCard.Answer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit">Create Card</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index" asp-route-id="@ViewBag.DeckId"> Back To Home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

aspnet_mvc/CardCram.Client/Views/Card/CreateCard.cshtml
@model CardCram.Client.Models.CardViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Your Card</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="create" asp-controller="card" asp-antiforgery="true" method="GET">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input type="hidden" name="NewCard.DeckId" value="@ViewBag.DeckId"/>
            </div>
            <div class="form-group">
                <label asp-for="Question" class="control-label"></label>
                <input asp-for="Question" name = "Question" class="form-control"/>
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Answer" class="control-label"></label>
                <input asp-for="Answer" name = "Answer" class="control-label"/>
                <span asp-validation-for="Answer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit">Create Card</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index" asp-route-id="@ViewBag.DeckId"> Back To Home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

aspnet_mvc/CardCram.Client/Views/Card/Delete.cshtml
@model CardCram.Client.Models.DeckViewModel

@{
    ViewData["Title"] = "Delete";
}

<p>Current cards:</p>

@foreach (var card in Model.Cards)
{
    @card.Question;
}

<a asp-controller="Home" asp-action="Index"> Back To Home </a>

aspnet_mvc/CardCram.Client/Views/Card/DeleteCard.cshtml
@model CardCram.Client.Models.DeckViewModel

@{
    ViewData["Title"] = "Delete";
}

<p>Current cards:</p>

@foreach (var card in Model.Cards)
{
    @card.Question;
}

<a asp-controller="Home" asp-action="Index"> Back To Home </a>

aspnet_mvc/CardCram.Client/Views/Card/ViewCards.cshtml
@model CardCram.Client.Models.DeckViewModel

@{
    ViewData["Title"] = "View";
}

<p>The answer is right below the question; highlight it to see it.</p>

@foreach (var card in Model.Cards)
{
    @card.Question;<br>
    <p style="color: white">@card.Answer</p>
}

<br>
<form asp-action="Index" asp-controller="Home" asp-antiforgery="true" method="GET">
    <button type="submit">Back To Home</button>
</form>

aspnet_mvc/CardCram.Client/Views/Deck/Create.cshtml
@model CardCram.Client.Models.DeckViewModel

@{
    ViewData["Title"] = "Create";
}

<h1> Create your Deck </h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index" asp-route-id="@ViewBag.DeckId"> Back To Home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

aspnet_mvc/CardCram.Client/Views/Deck/CreateDeck.cshtml
@model CardCram.Client.Models.DeckViewModel

@{
    ViewData["Title"] = "Create";
}

<h1> Create your Deck </h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control"/>
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="Index" asp-route-id="@ViewBag.DeckId"> Back To Home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

aspnet_mvc/CardCram.Client/Views/Deck/Delete.cshtml
@model CardCram.Client.Models.CardViewModel

@{
    ViewData["Title"] = "Delete";
}


<h1> Are you sure you want to delete this deck? </h1>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(Model => Model.Question)
        </dt>
        <dd>
            @Html.DisplayFor(Model => Model.Question)
        </dd>
        <dt>
            @Html.DisplayNameFor(Model => Model.Answer)
        </dt>
        <dd>
            @Html.DisplayFor(Model => Model.Answer)
        </dd>
        <dt>
            @Html.DisplayNameFor(Model => Model.Deck)
        </dt>
        <dd>
            @Html.DisplayFor(Model => Model.Deck.Title)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="CardId"/>
        <input type="submit" value="Delete" class="btn btn-default"/>
    </form>
    
    <a asp-controller="Home" asp-action="Index"> Back To Home </a>
</div>

aspnet_mvc/CardCram.Client/Views/Deck/DeleteDeck.cshtml
@model CardCram.Client.Models.CardViewModel

@{
    ViewData["Title"] = "Delete";
}


<h1> Are you sure you want to delete this deck? </h1>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(Model => Model.Question)
        </dt>
        <dd>
            @Html.DisplayFor(Model => Model.Question)
        </dd>
        <dt>
            @Html.DisplayNameFor(Model => Model.Answer)
        </dt>
        <dd>
            @Html.DisplayFor(Model => Model.Answer)
        </dd>
        <dt>
            @Html.DisplayNameFor(Model => Model.Deck)
        </dt>
        <dd>
            @Html.DisplayFor(Model => Model.Deck.Title)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="CardId"/>
        <input type="submit" value="Delete" class="btn btn-default"/>
    </form>
    
    <a asp-controller="Home" asp-action="Index"> Back To Home </a>
</div>

aspnet_mvc/CardCram.Client/Views/Home/Index.cshtml
@model CardCram.Client.Models.DeckViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome To CardCram! </h1>

    <p>
        Didn't get enough time to study for a test? Or do you need some quick refresh notes on a certain subject?
        CardCram is here to help! We have a selection of pre-made subjects for you to study, memorize, and more.
        With CardCram, you can also make your own cards to export or share with classmates. Get CardCram-ming today!
    </p>
    
    <a asp-area="" asp-controller="Card" asp-action="Get">Add a Card</a><br>
    <a asp-area="" asp-controller="Card" asp-action="DeleteCard">Delete a Card</a><br>
    <a asp-area="" asp-controller="Deck" asp-action="CreateDeck">Create a Deck</a><br>
    <a asp-area="" asp-controller="Deck" asp-action="DeleteDeck">Delete a Deck</a><br>

</div>





<div>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

aspnet_mvc/CardCram.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CardCram</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CardCram</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @if (User.Identity.IsAuthenticated)
        {
            <p class="navbar-text">Hello, @User.Identity.Name</p>
        }
        else
        {
            <a asp-controller="Account" asp-action="SignIn">Sign In</a>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 Amulya Kakumanu, Monica Brown, Michael LaBarbiera
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>